twitter-to-kafka-serv:
   twitter-keywords:
     - Java
     - Microservices
     - Kafka
     - Elasticsearch
     - cricket
     - Royal Challengers Bangalore

   welcome-message:
    - warmly welcome you guys..........
